HomeBakesCSIA/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from recipes.views import recipes_list

#Import the url paths to the apps
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', recipes_list),
    path('recipes/',include('recipes.urls')),
    path('users/', include('users.urls')),
]

# Serves media files (like images) during development
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

# URL paths to the different pages
urlpatterns = [
    path('', views.recipes_list, name="list"),
    path('new-recipe/', views.recipe_new, name="new-recipe"),
    path('<slug:slug>', views.recipe_page, name="page"),
    path('<slug:slug>/bakenow/step<int:step>', views.bakenow, name='bakenow'),
    path('admin-panel/',views.admin_panel, name="admin-panel"),
    path('admin-panel/manage-recipes',views.manage_recipes_list,name="manage-recipes-list"),
    path('admin-panel/manage-recipes/<slug:slug>/', views.manage_recipes_list, name='delete-recipe'), 
    path('<slug:slug>/favourite', views.favourite, name='favourite'),
    path('<slug:slug>/tobake', views.tobake, name='tobake'),
    path('admin-panel/edit-recipe/<slug:slug>',views.edit_recipe,name="edit-recipe"),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('favourites/', views.favouriteslist, name='favourites'),
    path('tobake/', views.tobakelist, name='tobakes'),
    path('adminregister/', views.admin_register, name="adminregister"),
    path('password-reset/', views.request_password_reset, name='request_password_reset'),
    path('change-password/', views.change_password, name='change_password'),
    path('settings/',views.change_settings,name='change_settings')




]

recipes/models.py
#Imports
from django.db import models #Import Django models 

#Recipe model defines the attributes of a recipe, each attribute corresponds to a field in the database
class Recipe(models.Model):
    recipe_name = models.CharField(max_length=255)
    intended_serving_size = models.IntegerField() 
    measuring_system_choices = [(0, 'Metric'), (1, 'Imperial'),] #Defines measuring system choices that the recipe can be written in. Recipe measurements can only written in these predefined options
    measuring_system = models.IntegerField(choices = measuring_system_choices, default = 1) #Stores recipe's measuring system 
    slug = models.SlugField(unique=True, blank=True) #Slug for the recipe (used in URLs)
    date_created = models.DateTimeField(auto_now_add=True) 
    image = models.ImageField(default = 'fallback.png', blank=True) 

    def __str__(self): # When a Recipe object is printed/converted to a string, it's name is returned
        return self.recipe_name

#Instruction model defines the attributes of an instruction, each attribute corresponds to a field in the database
class Instruction(models.Model):
    recipe = models.ForeignKey('Recipe',on_delete=models.CASCADE,related_name='instructions') #ForeignKey linking an instruction to a recipe, 1 recipe can have multiple instructions
    step = models.IntegerField() 
    description = models.TextField()
    timer = models.BooleanField(default=False) 
    timer_time = models.FloatField(null=True, blank=True) #If a timer is needed, this field stores the duration (in minutes)

    def __str__(self): #When an Instruction object is printed/converted to a string, it's recipe's name and instruction step are returned
        return f"{self.recipe.recipe_name} - Step {self.step}"

#Ingredient model defines the attributes of an ingredient, each attribute corresponds to a field in the database
class Ingredient(models.Model):
    quantity = models.FloatField() 
    recipe = models.ForeignKey('Recipe',on_delete=models.CASCADE,related_name='ingredients')#ForeignKey linking an ingredient to a recipe, 1 recipe can have multiple ingredients
    uom_choices = [(0, 'cup'), (1, 'tbsp'), (2, 'tsp'), (3, 'oz'), (4, 'lbs'), (5, 'stick'),(6, 'ml'), (7, 'g'),(8,"")] #Set of predefined units of measurement to choose from
    uom = models.IntegerField(choices = uom_choices, default=8) #Unit of measurement for the ingredient 
    instruction = models.ForeignKey('Instruction',on_delete=models.CASCADE,related_name='ingredients')#ForeignKey linking an ingredient to an instruction, 1 instruction can have multiple ingredients
    ing_name = models.CharField(max_length=255)

    def __str__(self):  #When an Ingredient object is printed/converted to a string, 
                        #it's recipe's name and ingredient name are returned
        return f"{self.recipe.recipe_name} - {self.ing_name}"
    

recipes/forms.py
from django import forms 
from . import models #Import models

#Form for Creating a Recipe
class CreateRecipe(forms.ModelForm):
    class Meta:
        model = models.Recipe 
        fields = ['recipe_name','intended_serving_size','measuring_system',
                    'image'] # These fields will appear in the form for users to fill out

recipes/views.py
from django.shortcuts import render, redirect
from .models import Recipe, Instruction, Ingredient
from . import forms
from .decorators import admin_required
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from users.models import Profile
from django.urls import reverse
from .forms import CreateRecipe
from django.forms import inlineformset_factory

#Displays a list of all recipes
def recipes_list(request):
    query = request.GET.get('q')  #Retrieve user query
    all_recipes = Recipe.objects.all() 
    recipes = [] 

    if query: #Check is user has requested a query
        # Linear search implementation
        for recipe in all_recipes:
            if query.lower() in recipe.recipe_name.lower(): #Check if user query exists in recipe name
                recipes.append(recipe)
    else:
        recipes = list(all_recipes)

    # Bubble sort by date_created
    n = len(recipes) 
    for i in range(n): 
        for j in range(0, n-i-1):
            if recipes[j].date_created < recipes[j+1].date_created:
                recipes[j], recipes[j+1] = recipes[j+1], recipes[j]

    return render(request, 'recipes/recipes_list.html', {'recipes': recipes})

def uom_conversion(quantity, uom, target_system, ingredient_name,orig_system):
    #Dictionary to store conversion factor to convert imperial to metric and vice versa (multiply for conversion to metric system and divide for conversion to imperial)
    conversion_factors = {
        '0': 240,  # 1 cup is 240ml
        '3': 30,   # 1 ounce is 30g
        '5': 115,   # 1 stick (of butter) is 115 g

        # Specific ingredient conversions (Imperial to Metric)
        'flour': 120,  # 1 cup of flour is 120g
        'sugar': 200,  # 1 cup of sugar is 200g
    }

    #Dictionary to map numerical unit of measurement code to its actual name
    uom_names = {0: 'cup', 1: 'tbsp', 2: 'tsp', 3: 'oz', 4: 'lbs', 5: 'stick', 6: 'ml', 7: 'g', 8: ''}

    # Initialising the variables used to store adjusted measurements
    converted_quantity = quantity
    new_uom = uom

    if orig_system!=target_system:
        if target_system == 0: #if units need to be converted to metric
            if uom == 0: #converting all the cups
                #flour and sugar have different conversions from cups to grams
                if 'flour' in ingredient_name.lower(): 
                    converted_quantity = round(quantity * conversion_factors['flour'],2)
                    new_uom = 'g'
                elif 'sugar' in ingredient_name.lower():
                    converted_quantity = round(quantity * conversion_factors['sugar'],2)
                    new_uom='g'
                else: #converted to ml because if the ingredient is not flour or sugar, it would be a wet ingredient (which uses ml)
                    converted_quantity= round(quantity * conversion_factors['0'],2)
                    new_uom = 'ml'
            elif str(uom) in conversion_factors: #Convert the rest of the imperial measurements to their metric counterpart
                converted_quantity = round(quantity * conversion_factors[str(uom)],2)
                new_uom='g'
        
        elif target_system == 1: #Converted to imperial
            #flour, butter and sugar have different conversions
            if 'flour' in ingredient_name.lower():
                converted_quantity = round(quantity / conversion_factors['flour'],2)
                new_uom = 'cups'
            elif 'butter' in ingredient_name.lower():
                converted_quantity = round(quantity / conversion_factors['5'],2)
                new_uom='stick'
            elif 'sugar' in ingredient_name.lower():
                converted_quantity = round(quantity / conversion_factors['sugar'],2)
                new_uom='cups'
            elif uom == 6:
                converted_quantity = round(quantity / conversion_factors['0'],2)
                new_uom = 'cups'
            elif uom ==  7:
                converted_quantity = round(quantity / conversion_factors['3'],2)
                new_uom = 'oz'
        
        #tbsp and tsp and ingredients with no unit don't need to be converted, but they still need to be represented using their names rather than numerical code
        if uom in [1, 2, 8]:
            new_uom = uom_names[uom]
    
    # if the orig_system = target system, no conversions need to be made but units must still be  represented by its name instead of numerical code
    else:        
        new_uom = uom_names[uom]

    return converted_quantity, new_uom

def recipe_page(request,slug):
    #Retrieve all necessary data from databases
    recipe = Recipe.objects.get(slug=slug) 
    ingredients = recipe.ingredients.all()
    instructions = recipe.instructions.all().order_by('step')
    profile = Profile.objects.get(user=request.user) 
    favourite_recipes = profile.favourite.all()
    tobake_recipes = profile.tobake.all()
    uom_display = profile.measuring_system_preference 
    orig_uom = recipe.measuring_system 

    adjusted_ingredients = [] #Initialise to store adjusted ingredient quantities

    serving_size = recipe.intended_serving_size 
    if request.method=='POST': #Check if user has requested to change serving size
        serving_size = int(request.POST.get('serving_size', recipe.intended_serving_size))
        request.session['serving_size'] = serving_size #Store in session so serving size can be retrieved in the bakenow page without redefining it in every page

        adjusted_ingredients = []
        for ingredient in ingredients:
            adjusted_quantity = round(((ingredient.quantity/recipe.intended_serving_size) * serving_size),1)  #Calculate new ingredient quantity according to the new serving size
            converted_quantity, converted_uom = uom_conversion(adjusted_quantity, ingredient.uom, uom_display, ingredient.ing_name,orig_uom) #Convert the ingredient's unit of measurement if needed using previously defined uom_conversion function
            adjusted_ingredients.append({
                'quantity': converted_quantity,
                'uom': converted_uom,
                'name': ingredient.ing_name
            })   #Store the adjusted ingredient details

    else:    #If no serving size change, convert ingredients using the default serving size
        for ingredient in ingredients:
            converted_quantity, converted_uom = uom_conversion(ingredient.quantity, ingredient.uom, uom_display, ingredient.ing_name,orig_uom)
            adjusted_ingredients.append({
                'quantity': converted_quantity,
                'uom': converted_uom,
                'name': ingredient.ing_name
            })
    request.session['converted_adjusted_ingredients'] = serving_size  # Store in session


    return render(request, 'recipes/recipe_page.html', {'recipe': recipe,
                                                        'ingredients': adjusted_ingredients,
                                                        'instructions': instructions,
                                                        'favourite_recipes': favourite_recipes,
                                                        'tobake_recipes': tobake_recipes,
                                                        'serving_size': serving_size
                                                        })

def bakenow(request,slug,step): #Displays the step-by-step baking instructions for a recipe.
    #Retrieve all necessary data from databases
    recipe = Recipe.objects.get(slug=slug)
    instructions = recipe.instructions.all()
    profile = Profile.objects.get(user=request.user)
    uom_display = profile.measuring_system_preference
    orig_uom = recipe.measuring_system # Original unit of measurement used in the recipe

    #Serving size set by user can be retrieved for calculation without the user entering it again
    serving_size = request.session.get('serving_size', recipe.intended_serving_size)

    #Ensure the step number is within valid bounds
    if step < 0:
        step = 0 
    elif step >= instructions.count():
        step = instructions.count() - 1 

    #Get instructions/ingredients for this step specifically
    current_instruction = instructions.get(step=step+1) 
    related_ingredients = current_instruction.ingredients.all() 

    #Adjust ingredient quantities based on the selected serving size and unit of measurement
    adjusted_ingredients = []
    for ingredient in related_ingredients:
        adjusted_quantity = round(((ingredient.quantity/recipe.intended_serving_size) * serving_size),1)
        converted_quantity, converted_uom = uom_conversion(adjusted_quantity, ingredient.uom, uom_display, ingredient.ing_name, orig_uom)
        adjusted_ingredients.append({
            'quantity': converted_quantity,
            'uom': converted_uom,
            'name': ingredient.ing_name
        })

    #Set the timer if the current step requires one
    if current_instruction.timer == True:
        timer_time_seconds = current_instruction.timer_time * 60  #Convert minutes to seconds
    else:
        timer_time_seconds=0 

    materials = {
        'recipe': recipe,
        'current_instruction': current_instruction,
        'related_ingredients': adjusted_ingredients,
        'step': step,
        'total_steps': instructions.count(),
        'timer_time_seconds': timer_time_seconds,
    }
    return render(request,'recipes/bakenow.html', materials)

def favourite(request,slug): #Adds/removes recipes to/from "Favourites" collection
    user = request.user 
    recipe = Recipe.objects.get(slug=slug)  
    profile = Profile.objects.get(user=user) 
    
    #Check if the recipe is already in the user's favourite list
    if profile.favourite.filter(slug=slug).exists():
        profile.favourite.remove(recipe)  #Remove from favourites if already present
    else:
        profile.favourite.add(recipe) #Add to favourites if not present

recipes/templates/recipes/admin_panel.html
{% extends "layout.html" %}

{% block title %}
    admin-panel
{% endblock %}

{% block content %}
    <section>
        <h1>Admin Homepage</h1>
        <!-- Link to the recipe management page -->
        <a href="{% url "recipes:manage-recipes-list" %}" class="button">Manage recipes</a> 
        <!-- Link to the admin registration page -->
        <a href="{% url "users:adminregister" %}" class="button">Create admin</a>

    </section>
{% endblock %}

recipes/templates/recipes/bakenow.html
{% extends "layout.html" %}

{% block title %}
    Bakenow: {{recipe.recipe_name}}
{% endblock %}

{% block content %}
    <section>
        <div class="bakenow">
            {% comment %} Display which recipe and which step is being viewed {% endcomment %}
            <h1>
                Baking: {{recipe.recipe_name}} <br>
                Step: {{step |add:'1'}} of {{total_steps}}
            </h1>
            
            <a href="{% url 'recipes:page' slug=recipe.slug %}">Return</a>

            {% comment %} Display ingredients for this step {% endcomment %}
            {% if related_ingredients %}
                <h2>Ingredients for this step:</h2>
                <ul>
                    {% for ingredient in related_ingredients %}
                        {{ ingredient.quantity }} {{ ingredient.uom }} {{ ingredient.name }} <br>
                    {% endfor %}
                </ul>
            {% endif %}

            {% comment %} Display current instruction {% endcomment %}
            <p>{{ current_instruction.description }}</p>
            
            
            {% load static %}
            {% if current_instruction.timer %}
                <div class="timer-container">
                    <!-- Display the remaining time in seconds -->
                    <p class="timer">Time remaining: <span id="time">{{ timer_time_seconds }}</span> seconds</p>
                </div>

                <!-- Container for the control buttons -->
                <div class="buttons-container">
                    <button id="start" class="button">Start</button>
                    <button id="stop" class = "button">Pause</button>
                    <button id="reset" class="button">Reset</button>
                </div>

                <!-- Audio for the alarm sound that plays when time is up -->
                <audio id="alarmSound" src="{% static 'Alarm sound effect.mp3' %}" preload="auto"></audio>
                
                <script>
                    document.addEventListener('DOMContentLoaded', function() {
                        let timeRemaining = {{ timer_time_seconds }}; // Initialize the time remaining 
                        let changeTime; // Variable to store the time interval

                        //Retrieve timer display and control buttons
                        const timerElement = document.getElementById('time');
                        const startButton = document.getElementById('start');
                        const pauseButton = document.getElementById('stop');
                        const resetButton = document.getElementById('reset');

                        // Start the timer when the "Start" button is clicked
                        startButton.addEventListener('click', function() {
                            clearInterval(changeTime); // Clear any existing intervals to avoid multiple timers
                            changeTime = setInterval(updateTimer, 1000); // Start a new interval that updates every second
                        });
                        
                        // Pause the timer when the "Pause" button is clicked
                        pauseButton.addEventListener('click', function() {
                            clearInterval(changeTime);
                        });
                        
                        // Reset the timer when the "Reset" button is clicked
                        resetButton.addEventListener('click', function() {
                            clearInterval(changeTime); // Stop the interval
                            timeRemaining = {{ timer_time_seconds }}; // Reset time to the original value
                            timerElement.textContent = timeRemaining; // Update the displayed time
                        });

                        // Function to update the timer every second
                        function updateTimer() {
                            if (timeRemaining > 0) {
                                timeRemaining--; // Decrease the time remaining by 1 (second)
                                timerElement.textContent = timeRemaining; // Update the displayed time
                            } else {
                                clearInterval(changeTime); // Stop the timer when it reaches 0
                                alarmSound.play(); // Play an alarm sound
                                {% comment %} alert("Time's up!"); // Show an alert when the timer reaches zero {% endcomment %}
                            }
                        }
                    });
                </script>
            {% endif %}

            {% comment %} Buttons to go to the next/previous step {% endcomment %}
            <div class="nextpreviousbuttons {% if step == 0 %} no-previous{% endif %} ">
                {% if step > 0 %}
                    <a href="{% url 'recipes:bakenow' slug=recipe.slug step=step|add:'-1' %}" class="button">PREVIOUS</a>
                {% endif %}
                {% if step < total_steps|add:'-1' %}
                    <a href="{% url 'recipes:bakenow' slug=recipe.slug step=step|add:'1' %}" class="button">NEXT</a>
                {% endif %}
            </div>
        </div>
    </section>



{% endblock %}

recipes/templates/recipes/edit_recipe.html
{% extends "layout.html" %}

{% block title %}
    Editing {{recipe.recipe_name}}
{% endblock %}

{% block content %}
    <section class="edit_recipe">
        <h1>Editing "{{recipe.recipe_name}}" recipe</h1>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Recipe Form -->
            <h3>Recipe</h3>    
                {{ recipe_form.as_p }} 
            <button type="submit" name="save_recipe">Save Recipe Details</button>
        </form>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
        
            <!-- Instruction Formset -->
            <h3>Instructions</h3>
            {{ instruction_formset.management_form }}
        
            {% for form in instruction_formset %}
                    {{ form.as_p }} 
                    <hr> 
            {% endfor %}

            <button type="submit" name="save_instructions">Save Instructions</button>
        </form>

         <form method="POST">
            {% csrf_token %}

            <!-- Ingredient Formset -->
            <h3>Ingredients</h3>
            {{ ingredient_formset.management_form }}

            {% for form in ingredient_formset %}
                {{ form.as_p }}  
                <hr>
            {% endfor %}

            <button type="submit" name="save_ingredients">Save Ingredients</button>
        </form>

    </section>
{% endblock %}

recipes/templates/recipes/manage_recipes.html
{% extends "layout.html" %}

{% block title %}
    Manage recipes
{% endblock %}

{% block content %}
    <section>
        <h1>Manage Recipes</h1>
            <a class="button" href="{% url 'recipes:new-recipe'%}">Add recipe</a>
            <div id="recipe-list">
                {% for recipe in recipes %}
                    {% comment %} Hyperlink to the recipe's page {% endcomment %}
                    <div id="recipe-{{ recipe.slug }}" style="display: flex; align-items: center;">
                        <a href="{% url 'recipes:edit-recipe' slug=recipe.slug %}" style="flex-grow: 1;">
                            <h2>{{ recipe.recipe_name }}</h2>
                        </a>
                        {% comment %} Delete form {% endcomment %}
                        <form onsubmit="return confirm('Are you sure?');" action="{% url 'recipes:delete-recipe' recipe.slug %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="button">X</button>
                        </form>
                    </div>
                    
                {% endfor %}
            </div>
    </section>
    

{% endblock %}

recipes/templates/recipes/recipe_new.html
{% extends "layout.html" %}

{% block title %}
    Add a new recipe
{% endblock %}

{% block content %}
    <section>
        <h1>New Recipe</h1>
        {% comment %} Create recipe form {% endcomment %}
        <form class="form-with-validation" action="{% url 'recipes:new-recipe'%}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form}}
            {{form1}}
            <button class='form-submit'>Add Recipe</button>
        </form>
    </section>
{% endblock %}

recipes/templates/recipes/recipe_page.html
{% extends "layout.html" %}

{% block title %}
    {{recipe.recipe_name}}
{% endblock %}

{% block content %}
    <section>
        <h1>{{recipe.recipe_name}}</h1>
            <div class="recipePage">
                {% comment %} Image of the recipe {% endcomment %}
                <img 
                    style="float: right;"
                    class = "image"
                    src="{{ recipe.image.url }}" 
                    alt="{{ recipe.recipe_name }}"    
                />

                {% comment %} Add recipe to "Favourites" or "To Bake" collection {% endcomment %}
                <div class="button-container">
                    {% if recipe in favourite_recipes %}
                        <a href="{% url 'recipes:favourite' recipe.slug %}" class="button">
                            Remove from Favourites
                        </a>
                    {% else %}
                        <a href="{% url 'recipes:favourite' recipe.slug %}" class="button">
                            Add to Favourites
                        </a>
                    {% endif %}
                    {% if recipe in tobake_recipes %}
                        <a href="{% url 'recipes:tobake' recipe.slug %}" class="button">
                            Remove from To Bake
                        </a>
                    {% else %}
                        <a href="{% url 'recipes:tobake' recipe.slug %}" class="button">
                            Add to To Bake
                        </a>
                    {% endif %}
                </div>
                
                {% comment %} Display ingredients {% endcomment %}
                <h2>Ingredients</h2>
                {% comment %} Form to input custom serving size {% endcomment %}
                <form method="post">
                    {% csrf_token %}
                    <label for="serving_size">Servings:</label>
                    <input type="number" id="serving_size" name="serving_size" value="{{ serving_size }}" min="1">
                    <button type="submit">Update</button>
                </form>
                {% comment %} CSS styling to be able to 'cross off' ingredients {% endcomment %}
                <ul class="ingredients">
                    {% for ingredient in ingredients %}
                        <label>
                            <input type="checkbox" class="checkbox"> 
                            <span>{{ ingredient.quantity }} {{ ingredient.uom }} {{ ingredient.name }}<br></span>
                        </label>
                    {% endfor %}
                </ul>

                {% comment %} Display instructions {% endcomment %}
                <h2>Instructions</h2>
                <ol class="instructions">
                    {% for instruction in instructions %}
                        <li>{{ instruction.description }}</li>
                    {% endfor %}
                </ol>

                {% comment %} "Bake now" button, brings user to the first instruction step {% endcomment %}
                <div class="button-container">
                    <a href="{% url 'recipes:bakenow' slug=recipe.slug step=0 %}" class="button">
                        Bake now!
                    </a>
                </div>
                
                
            </div>
    </section>
{% endblock %}

recipes/templates/recipes/recipes_list.html
{% extends "layout.html" %}

{% block title %}
    Recipes
{% endblock %}

{% block content %}
    <section>
    <h1>Recipes</h1>
    {% comment %} Form to input query to search for a recipe {% endcomment %}
    <form method="get" action="{% url 'recipes:list' %}">
        <input type="text" name="q" placeholder="Search recipes..." value="{{ request.GET.title }}">
        <input class="button" type="submit" value="Search">
    </form>
    {% comment %} Display all recipes {% endcomment %}
    <div class="recipe-list">
        {% for recipe in recipes %}
            <article class="recipe">
                <a href = "{% url 'recipes:page' slug=recipe.slug%}">
                    <img 
                        class = "image"
                        src="{{ recipe.image.url }}" 
                        alt="{{ recipe.recipe_name }}"
                    />
                    <h2> {{recipe.recipe_name }}</h2>
                </a>
            </article>

        {%endfor%}
    </div>

</section>
{% endblock %}