HomeBakesCSIA/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from recipes.views import recipes_list

#Import the url paths to the apps
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', recipes_list),
    path('recipes/',include('recipes.urls')),
    path('users/', include('users.urls')),
]

# Serves media files (like images) during development
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

# URL paths to the different pages
urlpatterns = [
    path('', views.recipes_list, name="list"),
    path('new-recipe/', views.recipe_new, name="new-recipe"),
    path('<slug:slug>', views.recipe_page, name="page"),
    path('<slug:slug>/bakenow/step<int:step>', views.bakenow, name='bakenow'),
    path('admin-panel/',views.admin_panel, name="admin-panel"),
    path('admin-panel/manage-recipes',views.manage_recipes_list,name="manage-recipes-list"),
    path('admin-panel/manage-recipes/<slug:slug>/', views.manage_recipes_list, name='delete-recipe'), 
    path('<slug:slug>/favourite', views.favourite, name='favourite'),
    path('<slug:slug>/tobake', views.tobake, name='tobake'),
    path('admin-panel/edit-recipe/<slug:slug>',views.edit_recipe,name="edit-recipe"),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('favourites/', views.favouriteslist, name='favourites'),
    path('tobake/', views.tobakelist, name='tobakes'),
    path('adminregister/', views.admin_register, name="adminregister"),
    path('password-reset/', views.request_password_reset, name='request_password_reset'),
    path('change-password/', views.change_password, name='change_password'),
    path('settings/',views.change_settings,name='change_settings')




]

users/models.py
#Imports
from django.db import models  #Import Django models 
from django.contrib.auth.models import User #Import Django User model
from recipes.models import Recipe #Import Recipe model from recipes app

#Profile model extends functionality of an object of Django's User model by adding additional attributes (meaasuring_system_preferences, is_admin, favourite, tobake)
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #Establishes a one-to-one relationship with Django's built-in User model. Each profile is linked to a unique User object

    measuring_system_choices = [(0, 'Metric'), (1, 'Imperial'),] #Defines user's measuring system choices. User can only choose from a dropdown menu of predefined options

    measuring_system_preference = models.IntegerField(choices = measuring_system_choices, default = 1)#Stores user's measuring system preference

    is_admin = models.BooleanField(default=False) 

    favourite = models.ManyToManyField(Recipe, related_name='favourite_recipes') #Many-to-many relationship with the Recipe model to store the recipes that the user has marked as favourites

    tobake = models.ManyToManyField(Recipe,related_name='tobake_recipes') #Many-to-many relationship with the Recipe model to store the recipes that the user wants to bake

    def __str__(self): #when a Profile object is printed/converted to a string, its username is returned
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User 
from .models import Profile 
from django.contrib.auth.forms import UserCreationForm 

#Custom User Registration Form which extends Django's built-in UserCreationForm
class UserRegistrationForm(UserCreationForm):
    is_admin = forms.BooleanField(required=False) #Add is_admin field to the form
    class Meta:
        model = User 
        fields = ['username', 'email', 'password1','password2', 'is_admin'] #These fields will appear in the sign-up form. 'username', 'email', 'password1','password2' are all from Django's UserCreationForm, but 'is_admin' is from this custom form. 
    
#Form for Changing the Measuring System Preference
class changeMeasuringSystem(forms.ModelForm):
    class Meta:
        model = Profile 
        fields = ['measuring_system_preference']

users/views.py
from django.shortcuts import render, redirect  #Used to render templates and redirect users
from django.contrib.auth.forms import AuthenticationForm #Import Django's Authentification form used for login
from django.contrib.auth import login,logout #Import Django's login/logout function
from .models import Profile #Import Profile class from models.py file
from django.contrib.auth.decorators import login_required #Decorator to restrict access to certain views
from .utils import send_password_reset_email  #Import function defined in utils.py
from .forms import changeMeasuringSystem, UserRegistrationForm #Import forms defined in forms.py file
from recipes.decorators import admin_required #Import decorator defined in decorators.py in recipes folder

# View for customer registration (non-admin users)
def register_view(request):
    if request.method == "POST": #Checks if the form is submitted from the register.html file
        form = UserRegistrationForm(request.POST) #Create a form instance with POST data
        if form.is_valid(): #Check if the data entered is valid
            user = form.save()
            Profile.objects.create(user=user, is_admin=False) #Uses the newly created user to create a profile for them (not an admin)
            login(request, user) #Log them in automatically
            return redirect("recipes:list") #Bring user to the recipe list page
    else:
        form = UserRegistrationForm() #Show an empty form if user hasn't submitted anything
    return render(request, "users/register.html",{ "form": form })

@admin_required #Restricted access to only admin users
def admin_register(request):
    if request.method == "POST": #Checks if the form is submitted from the adminregister.html file
        form = UserRegistrationForm(request.POST)#Create a form instance with POST data
        if form.is_valid():#Check if the data entered is valid
            user = form.save()
            Profile.objects.create(user=user, is_admin=True)#Uses the newly created user to create a profile for them (is an admin)
            return redirect("recipes:list")  #Bring user to the recipe list page
    else:
        form = UserRegistrationForm()#Show an empty form if user hasn't submitted anything
    return render(request, "users/adminregister.html",{ "form": form })

#Displays login form
def login_view(request): 
    if request.method == "POST": #Check if form has been submitted from the login.html
        form = AuthenticationForm(data=request.POST) #Create a form instance with POST data
        if form.is_valid(): 
            user = form.get_user() 
            login(request, user) 
            if user.profile.is_admin:  #Conditional to redirect based on user type
                return redirect("recipes:admin-panel")
            else:
                return redirect("recipes:list")
    else:
        form = AuthenticationForm() 
    return render(request, "users/login.html", {"form": form})

#Allows user to request a link to reset their password
def request_password_reset(request):
    if request.method == "POST": 
        email = request.POST.get("email") 
        user = Profile.objects.filter(user__email=email).first() #Finds user with the given email exists
        if user: #checks if user exists
            reset_link = "http://localhost:8000/users/change-password/" 
            send_password_reset_email(email, reset_link) #calls function defined in utils.py
            return redirect("http://127.0.0.1:8000/") 
        else:  #Show an error message if the email is not found
            return render(request, "users/request_password_reset.html", {"error": "User does not exist"})
    return render(request, "users/request_password_reset.html")

#Function to change password
def change_password(request): 
    messages = ""
    if request.method == 'POST': 
        email = request.POST.get('email') 
        first_entry = request.POST.get('first_entry')  #First password entry 
        new_password = request.POST.get('new_password') #Second password entry
        try:
            profile = Profile.objects.get(user__email=email) 
            user = profile.user 
            #Double entry verification
            if first_entry==new_password: 
                user.set_password(new_password) 
                user.save()
                messages = 'Password successfully updated!'
                return redirect('users:login') 
            else: messages=  'Passwords not the same' #Error message for mismatched passwords
        except Profile.DoesNotExist: #If email doesn't match any user profile, display this error message
            messages = (request, 'User not found.')
    return render(request, 'users/changepassword.html',{'messages':messages})

@login_required #Function is only visible to logged-in users
def logout_view(request):
    if request.method == "POST": #Check if form has been submitted
        logout(request)
        return redirect("recipes:list")

@login_required #Function is only visible to logged-in users
def favouriteslist(request):
    profile = Profile.objects.get(user=request.user) #Get the profile associated with the logged-in user
    favourite_recipes = profile.favourite.all() #Retrieve all favourite recipes linked to the profile
    return render(request, 'users/favourites.html', {'favourite_recipes': favourite_recipes})

@login_required #Function is only visible to logged-in users
def tobakelist(request):
    profile = Profile.objects.get(user=request.user) #Get the logged-in user's profile
    tobake_recipes = profile.tobake.all() #Retrieve all to-bake recipes linked to the profile
    return render(request, 'users/tobake.html', {'tobake_recipes': tobake_recipes})

@login_required #Function is only visible to logged-in users
def change_settings(request):
    profile = Profile.objects.get(user=request.user) #Get the logged-in user's profile
    
    if request.method == 'POST': #Check if form has been submitted through changesettings.html
        form = changeMeasuringSystem(request.POST, instance=profile)  #Use the data fromt the form to update the existing profile instead of creating a new one
        if form.is_valid():
            form.save()
            return redirect('users:change_settings')  #Redirect back to the settings page after saving
    else:
        form = changeMeasuringSystem(instance=profile) #Initialize form with existing profile data
    
    return render(request, 'users/changesettings.html', {'form': form})

users/templates/users/adminregister.html
{% extends "layout.html" %}

{% block title %}
    Admin Registration
{% endblock %}

{% comment %} {% block content %}
    <h1>Create Admin</h1>
    <form class="form-with-validation" action="{% url 'users:adminregister' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %} {% endcomment %}

{% block content %}
    <div class="form-wrapper"> 
        <div class="form-container">
            <h1>Create Admin</h1>
            <!-- Form for admin registration -->
            <form class="form-with-validation" action="{% url 'users:adminregister' %}" method="post">
                {% csrf_token %}
                
                <!-- Loop through form fields and render them to make them look better -->
                {% for field in form %}
                    {% if field.name != "is_admin" and field.label != "Password-based authentication" %}  
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}

                            <!-- Display field-specific error message if any -->
                            {% if field.errors %}
                                <p class="error-message">{{ field.errors.0 }}</p>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}

                <button type="submit" class="form-submit">Register</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/changepassword.html
{% extends 'layout.html' %}

{% block title %}
    Change Password
{% endblock %}

{% block content %}
    <h1>Change Password</h1>
    <form method="post">
        {% csrf_token %}
        <!-- Email input field -->
        <label for="email">Email:</label>
        <input type="text" name="email" required>
    
        <!-- New password input field -->
        <label for="first_entry">New Password:</label>
        <input type="password" name="first_entry" required>

        <!-- Confirm new password input field -->
        <label for="new_password">Enter Password Again:</label>
        <input type="password" name="new_password" required>
        <button type="submit">Change Password</button>
    </form>
    
    <!-- Display messages (e.g., success or error messages) -->
    <h2>{{ messages }}</h2>
    
{% endblock %}

users/templates/users/changesettings.html
{% extends "layout.html" %}

{% block content %}
    <h2>Change Measuring System Preference</h2>
    <div class="form-wrapper">
        <div class="form-container">
            {% comment %} Change measuring system form {% endcomment %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="form-submit">Save</button>
            </form>
            {% comment %} Link to change password view {% endcomment %}
            <p>
                <a href="{% url 'users:change_password' %}">Change Password</a>
            </p>
        </div>
    </div>
    
{% endblock %} 

users/templates/users/favourites.html
{% extends 'layout.html' %}

{% block title %}
    Favourites
{% endblock %}

{% block content %}
    <h1>Your Favourite Recipes</h1>
    {% if favourite_recipes %}
            {% comment %} Display all recipes in the collection with an option form them to be removed {% endcomment %}
            {% for recipe in favourite_recipes %}
                <div class="button-container">
                    <h2><a href = "{% url 'recipes:page' slug=recipe.slug%}">{{ recipe.recipe_name }}</a></h2> 
                    <a href="{% url 'recipes:favourite' recipe.slug %}" class='button'>Remove</a>
                </div>
            {% endfor %}
            
    {% else %}
        <h2>No recipes added...</h2>
    {% endif %}
{% endblock %}

users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
    User Login
{% endblock %}

{% block content %}
    <div class="form-wrapper">  
        <div class="form-container">
            {% comment %} Form to login {% endcomment %}
            <h1>User Login</h1>
            <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
                {% csrf_token %}

                {% comment %} Username input {% endcomment %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" required>
                </div>
                
                <!-- Password Input -->
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" required>
                </div>

                <button type="submit" class="form-submit">Login</button>
            </form>
            
            <!-- Display login error message if exists -->
            {% if error %}
                <p class="error-message">{{ error }}</p>
            {% endif %}

            <p><a href="{% url 'users:request_password_reset' %}">Forgot Password?</a></p>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
    User Registration
{% endblock %}

{% block content %}
    <div class="form-wrapper">
        <div class="form-container">
            <h1>User Registration</h1>
            {% comment %} User registration form {% endcomment %}
            <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
                {% csrf_token %}
                
                {% for field in form %}
                    {% if field.name != "is_admin" and field.label != "Password-based authentication" %}  
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            
                            <!-- Display field-specific error message if any -->
                            {% if field.errors %}
                                <p class="error-message">{{ field.errors.0 }}</p>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}

                <button type="submit" class="form-submit">Register</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/request_password_reset.html
{% extends "layout.html" %}

{% block title %}
    Request Password Reset
{% endblock %}

{% block content %}
    <h1>Password reset</h1>
    {% comment %} Change password form {% endcomment %}
    <form method="post">
        {% csrf_token %}
        {% comment %} Email input field {% endcomment %}
        <label for="email">Enter your email:</label>
        <input type="email" name="email" required>
        <button type="submit">Reset Password</button>
    </form>
    {% comment %} Display any error messages {% endcomment %}
    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}
{% endblock %}

users/templates/users/tobake.html
{% extends 'layout.html' %}

{% block title %}
    To Bake
{% endblock %}

{% block content %}
<h1>Your To Bake Recipes</h1>
    {% if tobake_recipes %}
        {% comment %} Display all recipes in the collection with an option form them to be removed {% endcomment %}
        {% for recipe in tobake_recipes %}
            <div class="button-container">
                <h2><a href = "{% url 'recipes:page' slug=recipe.slug%}">{{ recipe.recipe_name }}</a></h2> 
                <a class="button" href="{% url 'recipes:tobake' recipe.slug %}" class="button">Remove</a>
            </div>
        {% endfor %}
        
    {% else %}
        <h2>No recipes added...</h2>
    {% endif %}
{% endblock %}