HomeBakesCSIA/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from recipes.views import recipes_list

#Import the url paths to the apps
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', recipes_list),
    path('recipes/',include('recipes.urls')),
    path('users/', include('users.urls')),
]

# Serves media files (like images) during development
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

# URL paths to the different pages
urlpatterns = [
    path('', views.recipes_list, name="list"),
    path('new-recipe/', views.recipe_new, name="new-recipe"),
    path('<slug:slug>', views.recipe_page, name="page"),
    path('<slug:slug>/bakenow/step<int:step>', views.bakenow, name='bakenow'),
    path('admin-panel/',views.admin_panel, name="admin-panel"),
    path('admin-panel/manage-recipes',views.manage_recipes_list,name="manage-recipes-list"),
    path('admin-panel/manage-recipes/<slug:slug>/', views.manage_recipes_list, name='delete-recipe'), 
    path('<slug:slug>/favourite', views.favourite, name='favourite'),
    path('<slug:slug>/tobake', views.tobake, name='tobake'),
    path('admin-panel/edit-recipe/<slug:slug>',views.edit_recipe,name="edit-recipe"),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('favourites/', views.favouriteslist, name='favourites'),
    path('tobake/', views.tobakelist, name='tobakes'),
    path('adminregister/', views.admin_register, name="adminregister"),
    path('password-reset/', views.request_password_reset, name='request_password_reset'),
    path('change-password/', views.change_password, name='change_password'),
    path('settings/',views.change_settings,name='change_settings')




]

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href = "{% url "recipes:list" %}"> Recipes List 🍽️ </a> |
        {% if user.profile.is_admin %}
            <a href = "{% url "recipes:admin-panel" %}"> Admin Homepage </a> |
        {% endif %}
        {% if user.is_authenticated  %}
            <a href = "{% url "users:favourites" %}"> Favourite recipes </a> |
            <a href = "{% url "users:tobakes" %}"> To Bake recipes </a> |
            <a href="{% url 'users:change_settings' %}">Settings</a> |
            <form class = "logout" action="{% url "users:logout" %}" method="post">
                {% csrf_token %}
                <button class = "logout-button" title="User Logout"> Logout </button>
            </form>

        {% else %}
            <a href = "{% url "users:register" %}"> Register </a> |
            <a href = "{% url "users:login" %}"> Login </a> 
        {% endif %}


    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>